<a href="https://colab.research.google.com/github/SimonT2003/MAT422/blob/main/HW_1.2_Elements_of_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Elements of Linear Algebra in Python**

The following are the important topics in linear algebra that will be discussed:

*   1.2.1 - **Linear Spaces**
  *   1.2.1.1 - Linear Combinations
  *   1.2.1.2 - Linear Subspaces
  *   1.2.1.3 - Span
  *   1.2.1.4 - Linear Independence and Dimension
*   1.2.2 - **Orthogonality**
  - 1.2.2.1 - Orthonormal Bases
* 1.2.3 - **Projection**
- 1.2.4 - **Gram-Schmidt Process**
- 1.2.5 - **Eigenvalues and Eigenvectors**












## **Introduction to Linear Algebra**

Linear algebra is a significant field of mathematics. Linear algebra is primarily concerned with vectors and linear functions. It is used mostly in physics and engineering to define fundamental objects like planes, lines, and object rotations. It enables us to mimic numerous natural events while also being computationally efficient.

For data science, linear algebra is behind all the practical ML algorithms that data scientists used. According to Khyati Mahendru from Analytics Vidhya, she said: "If Data Science was Batman, Linear Algebra would be Robin". Sometimes the sidekick are often ignored. So, linear algebra is a must-know subject in data science to truly understand what's happening behind the curtains.  




## **Main Package for Linear Algebra in Python**

The main package for linear algebra in Python is the SciPy subpackage scipy.linalg which builds on NumPy.

In [1]:
import numpy as np
import scipy.linalg as la

## **Pre-Start: NumPy Arrays**

NumPy is used to work with arrays.

In [ ]:
A = np.array([1, 2, 3, 4, 5]) # This creates a 1-dimension array
print(A)

[1 2 3 4 5]


In [ ]:
print(A.ndim) # This shows that A is a 1-dimension array

1


In [ ]:
print(A.shape) # Shape of array A. In this case only the length is shown because it is a 1D array

(5,)


In [ ]:
print(A.size) # Size or number of elements of array A

5


In [ ]:
B = np.array([[1,3],[4,5],[7,9]]) # This creates a 2-dimension array (matrix)
print(B)

[[1 3]
 [4 5]
 [7 9]]


In [ ]:
print(B.ndim) # This shows that A is a 2-dimension array

2


In [ ]:
print(B.shape) # This is a 3x2 matrix

(3, 2)


In [ ]:
print(B.size) # The length or size or the # of elements in matrix B is 6

6


In [ ]:
col_1 = B[:,0] # This selects the first column of matrix B
print(col_1)

[1 4 7]


In [ ]:
col_2 = B[:,1] # This selects the second column of matrix B
print(col_2)

[3 5 9]


In [ ]:
row_1 = B[0,:] # This selects the first row of matrix B
print(row_1)

row_2 = B[1,:] # This selects the second row of matrix B
print(row_2)

row_3 = B[2,:] # This selects the third row of matrix B
print(row_3)

[1 3]
[4 5]
[7 9]


## **1.2.1 - Linear Spaces**

### **1.2.1.1 - Linear Combination**

Definition - Linear Combination

A ***linear combination*** of a list $v_1, v_2, ..., v_n$ of vectors in $V$ is a vector of the form

$a_1v_1 + a_2v_2 +...+ a_nv_n$,

where $a_1,a_2,...,a_n \in F$.

$F$ denotes $\mathbb{R}$ or $\mathbb{C}$


In [ ]:
# Ex. Let's define a1, a2, and a3
a1 = 5
a2 = 4
a3 = 7

# Let's define vectors v1, v2, and v3
v1 = np.array([1, 2])
v2 = np.array([3, 4])
v3 = np.array([5, 6])

# Compute the linear combination
linear_combination = a1*v1 + a2*v2 + a3*v3

print("Linear combination result:", linear_combination)

Linear combination result: [52 68]


### **1.2.1.2 - Linear Subspace**

A subset $U⊆V$ is called a ***subspace*** of $V$ if and only if $U$ satistifes the following three conditions:

* **additive identity**:  $0\in$ $U$
* **closed under addition**: $u, w \in U$ implies $u + w \in U$
* **closed under scalar multiplication**: $a \in F$ and $u \in U$ implies $a \cdot u \in U$.

In [ ]:
u = np.array([3,2])
w = np.array([6,4])
print(u+w,'is also in U')
a = 5
print(a*u, 'is also in U')

[9 6] is also in U
[15 10] is also in U


### **1.2.1.3 - Span**

The set of all linear combinations of a list of vectors $v_1,...,v_m$ in $V$ is called the **span** of $v_1,...,v_m$, denoted span($v_1,...,v_m$). In other words,

span($v_1,...,v_m$) $= \{a_1v_1+...+a_mv_m:a_1,...,a_m\in F\}$.

The span of the empty list ( ) is defined to be {0}.

### **1.2.1.4 - Linear Independence and Dimension**


*   A list $v_1,...,v_m$ of vectors in $V$ is called **linearly independent** if the only choice of $a_1,...,a_m \in F$ that makes $a_1v_1+...+a_mv_m=0.$
*   The empty list () is also declared to be linearly independent.



Example 1

Consider a matrix A, determine if columns of A are linearly independent.

\begin{align}
A = \begin{bmatrix}
0 & 1 & 4 \\
1 & 2 & -1 \\
5 & 8 & 0
\end{bmatrix}
\end{align}


Solve the system via augmented matrix

In [ ]:
import sympy as sy

A = sy.Matrix([[0,1,4,0],[1,2,-1,0],[5,8,0,0]])
A.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0]]),
 (0, 1, 2))

**$Ax=0$** has only trivial solution, i.e. $(c_1,c_2,c_3)^T=(0,0,0)$, so the columns of $A$ are linearly independent.

### **Linearly Dependent**

*   A list of vectors in $V$ is called **linearly dependent** if it is not linearly independent.
*   In other words, a list $v_1,...,v_m$ of vectors in $V$ is linear dependent if there exist $a_1,...,a_m\in F$, not all 0, such that $a_1v_1+...+a_mv_m=0.$



Example 2

$(2,3,1),(1,-1,2),(7,3,8)$ is linearly dependent in $F^3$ because

\begin{align}
2(2,3,1)+3(1,-1,2)+(-1)(7,3,8)=(0,0,0)
\end{align}

Definition - **dimension**, dim $V$



*   The **dimension** of a finite-dimensional vector space is the length of any basis of the vector space.
*   The dimension of $V$ (if $V$ is finite-dimensional) is denoted by dim $V$.



## 1.2.2 - Orthogonality

### 1.2.2.1 - Orthonormal Bases

Definition - **orthonormal**



*   A list of vectors is called **orthonormal** if each vector in the list has norm 1 and is orthogonal to all the other vectors in the list.
*   In other words, a list $e_1,...,e_m$ of vectors in $V$ is orthonormal if
\begin{align}
\langle e_j,e_k \rangle = \left\{
        \begin{array}{cl}
        1 & if\ j = k \\
        0 & if \ j \neq k.
        \end{array}
        \right.
\end{align}



Definition - **Norm and Inner Product**

$⟨u,v⟩ = u ⋅ v= \sum_{i=1}^n u_i v_i $ and $\lvert \lvert u \rvert \rvert = \sqrt{\sum_{i=1}^n u_i^2}$

In [ ]:
u = np.array([2,2])
v = np.array([4,4])

# Inner product
LHS = u@v
RHS = u[0]*v[0]+u[1]*v[1]
print(LHS ,'is equal to ', RHS)

16 is equal to  16


In [ ]:
# Norm
import math
LHS2 = math.sqrt(u[0]**2+u[1]**2)
RHS2 = np.linalg.norm(u)
print(LHS2 ,'is equal to ', RHS2)

# The following also gives the norm
RHS3 = math.sqrt(u@u)
print(RHS3)

2.8284271247461903 is equal to  2.8284271247461903
2.8284271247461903


## 1.2.3 - Projection

The length of a given vector’s shadow cast over another vector is the vector projection of one vector over another vector. It’s calculated by multiplying the magnitude of the two vectors by the cosecant of the angle between them. A scalar value is the outcome of a vector projection formula.

\begin{align}
proj_\vec u (\vec v) = \frac{\vec u ⋅ \vec v}{\lvert \lvert \vec u \rvert \rvert^2} ⋅ \vec u
\end{align}

In [2]:
# Define vectors u and v
u = np.array([1, 2, 3])   # vector u
v = np.array([5, 6, 2])   # vector v:

# Task: Project vector v on vector u

# finding norm of the vector v
u_norm = np.sqrt(sum(u**2))

# Apply the formula as mentioned above
# for projecting a vector onto another vector
# find dot product using np.dot()
proj_of_v_on_u = (np.dot(u, v)/u_norm**2)*u

print("Projection of Vector v on Vector u is: ", proj_of_v_on_u)

Projection of Vector v on Vector u is:  [1.64285714 3.28571429 4.92857143]


## 1.2.4 - Gram-Schmidt Process

The Gram-Schmidt process (or procedure) is a sequence of operations that allow us to transform a set of linearly independent vectors into a set of orthonormal vectors that span the same space spanned by the original set.

$\vec u_1= \vec v_1$, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $e_1= \frac{\vec u_1}{\lvert \lvert \vec u_1 \rvert \rvert}$

$\vec u_2=\vec v_2 \ - \text{proj}_{\vec u_1} (\vec v_2)$, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $e_2=\frac{\vec u_2}{\lvert \lvert \vec u_2 \rvert \rvert}$


$\vec u_3=\vec v_3 \ - \text{proj}_{\vec u_1} (\vec v_3) - \text{proj}_{\vec u_2} (\vec v_3)$, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$e_3=\frac{\vec u_3}{\lvert \lvert \vec u_3 \rvert \rvert}$

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$\vdots$ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$\vdots$

$\vec u_k=\vec v_k \ - \sum_{j=1}^{k=1}\text{proj}_{\vec u_j} (\vec v_k)$,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$e_k=\frac{\vec u_k}{\lvert \lvert \vec u_k \rvert \rvert}$




In [3]:
print ("Simple Example:")
import numpy as np
A = [6]
v1 = np.array(A)
print ("Vector A")
print (v1)
print ("R^1 = span of vector A")
print ("Vector B = Vector A divided by length of Vector A.")
np.linalg.norm(A)
mult = v1/np.linalg.norm(A)
print ("Vector B =", mult)
print ("Vector B is orthonormal.")

Simple Example:
Vector A
[6]
R^1 = span of vector A
Vector B = Vector A divided by length of Vector A.
Vector B = [1.]
Vector B is orthonormal.


## 1.2.5 - Eigenvlues and Eigenvectors

Definition - eigenvalue

Let $T \in \mathbb{R}^{d\times d}$ be a square matrix. A number $λ \in F$ is called an **eigenvalue** of $T$ if there exists $v \in V$ such that $v \neq 0$ and $Tv=λv$.

Definition - eigenvector

Let $T \in \mathbb{R}^{d\times d}$ be a square matrix and $λ \in F$ is an eigenvalue of $T$. A vector $v \in V$ is called an **eigenvector** of $T$ corresponding to $λ$ if $v \neq 0$ and $T\vec v=λ\vec v$.

Let $T$ be a square matrix. A non-zero vector $\vec v$ is an eigenvector for T with eigenvalue $λ$ if

\begin{align}
T\vec v=λ \vec v
\end{align}

Rearranging the equation, we see that $\vec v$ is a solution of the homogeneous system of equations

\begin{align}
(T-λI)\vec v=0
\end{align}

where $I$ is the identity matrix of size $n$. Non-trivial solutions exist only if the matrix **$T-λI$** is singular which means that **$det(T-λI)=0$**. Therefore eigenvalues are roots of the characteristic polynomial

\begin{align}
p(λ)=det(T-λI)
\end{align}

In [4]:
#  Calculating the eigenvalues and eigenvectors for a square array with the eig function in numpy.linalg
from numpy.linalg import eig

a = np.array([[0, 2],
              [2, 3]])
w,v=eig(a)
print('The eigenvalues of A are:\n', w)
print('The corresponding eigenvectors are:\n', v)

The eigenvalues of A are:
 [-1.  4.]
The corresponding eigenvectors are:
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


## Other Important Topics Worth Knowing:

- Solving System of Linear Equations
- Cramer's Rule
- Determinant
- QR Factorization
- Best Approximation Theorem
- Cauchy-Schwartz Inequality
- Symmetric Matrices
- Constrained Optimization
- Linear Transformation


## **References**

*   Linear Algebra Done Right - Sheldon Axler
*   Python SciPy and NumPy for Linear Algebra - jljudge-gh (GitHub)
* Python for Linear Algebra - madonnaojorin (GitHub)

